### ISSUE TITLE
server install doesn't work

### ISSUE THREAD

**Issue by harryhoch** [geneontology/go-exp#1]
tb-lx-wireless-pittnet-150-212-108-243:widget-consumer harry$ node

> var g = require('go-exp-widget');
> undefined
> g.skelter(['oi','boy']);
> TypeError: undefined is not a function
>     at repl:1:3
>     at REPLServer.defaultEval (repl.js:132:27)
>     at bound (domain.js:254:14)
>     at REPLServer.runBound [as eval](domain.js:267:12)
>     at REPLServer.<anonymous> (repl.js:279:12)
>     at REPLServer.emit (events.js:107:17)
>     at REPLServer.Interface._onLine (readline.js:214:10)
>     at REPLServer.Interface._line (readline.js:553:8)
>     at REPLServer.Interface._ttyWrite (readline.js:830:14)
>     at ReadStream.onkeypress (readline.js:109:10)

**Comment by kltm** [comment]
@harryhoch did you run 

: npm install

in the directory first?

**Comment by harryhoch** [comment]
yes

**Comment by kltm** [comment]
Ugh, sorry, finally duplicated it. Something changed since the last push, Lemme see...

**Comment by kltm** [comment]
Actually, just the docs got out of phase. Updating that.

**Comment by harryhoch** [comment]
ok. better. thanks
